development:
  adapter: postgresql
  encoding: unicode
  database: tubalr
  pool: 5
  timeout: 5000
  username: Rick

test:
  adapter: postgresql
  encoding: unicode
  database: tubalr-test
  pool: 5
  timeout: 5000
  username: Rick